In [5]:
import pandas as pd
import openpyxl

**Começando visualização e tratamento dos dados de municipios**

In [49]:
#2023
df_resultados_metas2023 = pd.read_excel('./2023/DADOS/resultados_e_metas_municipios.xlsx')
df_alunos2023 = pd.read_csv('./2023/DADOS/TS_ALUNO.csv', sep=';', encoding='latin1')
df_estado2023 = pd.read_csv('./2023/DADOS/TS_ESTADO.csv', sep=';', encoding='latin1')
df_municipio2023 = pd.read_csv('./2023/DADOS/TS_MUNICIPIO.csv', sep=';', encoding='latin1')

In [50]:
#2024
df_resultados_metas2024 = pd.read_excel('./2024/DADOS/resultados_e_metas_municipios_2024.xlsx')
df_alunos2024 = pd.read_csv('./2024/DADOS/TS_ALUNO.csv', sep=';', encoding='latin1')
df_estado2024 = pd.read_csv('./2024/DADOS/TS_ESTADO.csv', sep=';', encoding='latin1')
df_municipio2024 = pd.read_csv('./2024/DADOS/TS_MUNICIPIO.csv', sep=';', encoding='latin1')

In [31]:
df_resultados_metas2023.head()

,ANO DA AVALIAÇÃO,CÓDIGO UF,SIGLA UF,CÓDIGO MUNICÍPIO,NOME DO MUNICÍPIO,REDE,PERCENTUAL DE ALUNOS ALFABETIZADOS (1),META 2024 (2),META 2025,META 2026,META 2027,META 2028,META 2029,META 2030,NIVEL ALFABETIZAÇÃO,PERCENTUAL DE PARTICIPAÇÃO
0,ANO,CO_UF,SG_UF,CO_MUNICIPIO,NO_MUNICIPIO,NO_TP_REDE,PC_ALUNO_ALFABETIZADO,META_FINAL_2024,META_FINAL_2025,META_FINAL_2026,META_FINAL_2027,META_FINAL_2028,META_FINAL_2029,META_FINAL_2030,NIVEIS_ALFABETIZACAO_2023,PC_AVALIADOS_LP
1,2023,11,RO,1100015,Alta Floresta D'Oeste,MUNICIPAL,64.55,67.078601,69.512028,71.841093,74.058634,76.159493,78.140434,80,3,89.37
2,2023,11,RO,1100023,Ariquemes,MUNICIPAL,62.3,65.216878,68.023909,70.706161,73.251889,75.652567,77.902777,80,3,89.79
3,2023,11,RO,1100031,Cabixi,MUNICIPAL,69.1,70.845029,72.530686,74.154438,75.714346,77.209042,78.6377,80,3,90.48
4,2023,11,RO,1100049,Cacoal,MUNICIPAL,62.51,65.390716,68.162817,70.81199,73.326986,75.699642,77.924781,80,3,84.44

In [35]:
df_alunos2023.head()

,NU_ANO_AVALIACAO,CO_UF,SG_UF,ID_ALUNO,TP_SERIE,ID_ESCOLA,TP_DEPENDENCIA,CO_MUNICIPIO,NO_MUNICIPIO,IN_PRESENCA_LP,IN_PREENCHIMENTO_LP,CO_CADERNO_LP,VL_PESO_ALUNO_LP,VL_PROFICIENCIA_LP,IN_ALFABETIZADO
0,2023,11,RO,11008701,2,60000001,3,1100205,Porto Velho,0,0,17,NaN,NaN,0
1,2023,11,RO,11008695,2,60000001,3,1100205,Porto Velho,1,1,17,1.045465,714.314857,0
2,2023,11,RO,11008687,2,60000001,3,1100205,Porto Velho,0,0,17,NaN,NaN,0
3,2023,11,RO,11008682,2,60000001,3,1100205,Porto Velho,1,1,17,1.045465,759.206313,1
4,2023,11,RO,11008729,2,60000001,3,1100205,Porto Velho,0,0,19,NaN,NaN,0

In [21]:
df_estado2023.head()

,NU_ANO_AVALIACAO,CO_UF,SG_UF,TP_SERIE,ID_TIPO_REDE,PC_ALUNO_ALFABETIZADO,VL_MEDIA_LP
0,2023,11,RO,2,2,58.65,751.4731
1,2023,11,RO,2,3,65.17,760.1971
2,2023,11,RO,2,5,64.60,759.4357
3,2023,13,AM,2,3,49.20,733.6637
4,2023,13,AM,2,5,52.20,736.4687

In [32]:
df_municipio2023.head()

,NU_ANO_AVALIACAO,CO_UF,SG_UF,CO_MUNICIPIO,NO_MUNICIPIO,TP_SERIE,ID_TIPO_REDE,PC_ALUNO_ALFABETIZADO,VL_MEDIA_LP
0,2023,11,RO,1100015,Alta Floresta D'Oeste,2,5,64.55,758.3304
1,2023,11,RO,1100015,Alta Floresta D'Oeste,2,3,64.55,758.3304
2,2023,11,RO,1100023,Ariquemes,2,3,62.30,757.0999
3,2023,11,RO,1100023,Ariquemes,2,5,62.30,757.0999
4,2023,11,RO,1100031,Cabixi,2,5,69.10,767.8763

Juntando as tabelas de anos diferentes em apenas uma tabela contendo todos os anos

In [51]:
df_alunos = pd.concat([df_alunos2023, df_alunos2024], ignore_index=False)
df_estado = pd.concat([df_estado2023, df_estado2024], ignore_index=False)
df_municipio = pd.concat([df_municipio2023, df_municipio2024], ignore_index=False)
df_resultados_metas = pd.concat([df_resultados_metas2023, df_resultados_metas2024], ignore_index=False)

In [52]:
df_alunos.columns = ['Ano', 'ID_UF', 'Sigla_UF', 'ID_Aluno', 'Serie', 'ID_Escola', 'Tipo_Escola', 'ID_Municipio', 'Nome_Municipio', 'Presenca', 'Preenchimento', 'ID_Caderno', 'Peso_Aluno', 'Proficiencia', 'Alfabetizado']
df_estado.columns = ['Ano', 'ID_UF', 'Sigla_UF', 'Serie', 'Tipo_rede', 'Pc_Aluno_Alfabetizado', 'Media_Nota_Avaliacao', 'PC_ALUNO_NIVEL_0_LP',	'PC_ALUNO_NIVEL_1_LP',	'PC_ALUNO_NIVEL_2_LP',	'PC_ALUNO_NIVEL_3_LP',	'PC_ALUNO_NIVEL_4_LP',	'PC_ALUNO_NIVEL_5_LP',	'PC_ALUNO_NIVEL_6_LP',	'PC_ALUNO_NIVEL_7_LP',	'PC_ALUNO_NIVEL_8_LP']
df_municipio.columns = ['Ano', 'ID_UF', 'Sigla_UF', 'ID_Municipio', 'Nome_Municipio', 'Serie', 'Tipo_rede', 'Pc_Aluno_Alfabetizado', 'Media_Nota_Avaliacao', 'PC_ALUNO_NIVEL_0_LP',	'PC_ALUNO_NIVEL_1_LP',	'PC_ALUNO_NIVEL_2_LP',	'PC_ALUNO_NIVEL_3_LP',	'PC_ALUNO_NIVEL_4_LP',	'PC_ALUNO_NIVEL_5_LP',	'PC_ALUNO_NIVEL_6_LP',	'PC_ALUNO_NIVEL_7_LP',	'PC_ALUNO_NIVEL_8_LP']
df_resultados_metas.columns = ['Ano', 'ID_UF', 'Sigla_UF', 'ID_Municipio', 'Nome_Municipio', 'Rede', 'Pc_Aluno_Alfabetizado', 'Meta_2024', 'Meta_2025', 'Meta_2026', 'Meta_2027', 'Meta_2028', 'Meta_2029', 'Meta_2030', 'NIVEIS_ALFABETIZACAO', 'Pc_Participacao', 'Pc_Alunos_Alfabetizados_2023', 'Pc_Alunos_Alfabetizados_2024']

In [58]:
df_alunos.head()

,Ano,ID_UF,Sigla_UF,ID_Aluno,Serie,ID_Escola,Tipo_Escola,ID_Municipio,Nome_Municipio,Presenca,Preenchimento,ID_Caderno,Peso_Aluno,Proficiencia,Alfabetizado
0,2023,11,RO,11008701,2,60000001,3,1100205,Porto Velho,0,0,17,NaN,NaN,0
1,2023,11,RO,11008695,2,60000001,3,1100205,Porto Velho,1,1,17,"1,0454651","714,3148573",0
2,2023,11,RO,11008687,2,60000001,3,1100205,Porto Velho,0,0,17,NaN,NaN,0
3,2023,11,RO,11008682,2,60000001,3,1100205,Porto Velho,1,1,17,"1,0454651","759,2063133",1
4,2023,11,RO,11008729,2,60000001,3,1100205,Porto Velho,0,0,19,NaN,NaN,0

In [56]:
df_municipio = df_municipio.astype(str).apply(lambda x: x.str.replace('.', ',', regex=False))
df_estado = df_estado.astype(str).apply(lambda x: x.str.replace('.', ',', regex=False))
df_alunos = df_alunos.astype(str).apply(lambda x: x.str.replace('.', ',', regex=False))
df_resultados_metas = df_resultados_metas.astype(str).apply(lambda x: x.str.replace('.', ',', regex=False))

In [71]:
df_alunos['AlfabetizadoINT'] = df_alunos['Alfabetizado'].astype(int)

In [62]:
#teste de medidas

taxa_alfabetizados_uf = (
    df_alunos.groupby('Sigla_UF')['AlfabetizadoINT']
    .mean()
)

In [63]:
taxa_alfabetizados_uf

Sigla_UF
AC    0.419676
AL    0.434257
AM    0.401272
AP    0.397569
BA    0.319424
CE    0.821100
DF    0.474402
ES    0.625678
GO    0.624702
MA    0.526393
MG    0.594436
MS    0.463975
MT    0.511769
PA    0.401056
PB    0.476143
PE    0.559788
PI    0.532643
PR    0.622608
RJ    0.448547
RN    0.304218
RO    0.565781
RS    0.456924
SC    0.469700
SE    0.333622
SP    0.521843
TO    0.396640
Name: AlfabetizadoINT, dtype: float64

In [73]:
taxa_alfabetizado_geral = (df_alunos['AlfabetizadoINT'] == 1).mean()
taxa_alfabetizado_geral

np.float64(0.5130678679079286)

In [57]:
df_alunos.to_csv('./DADOS_FINAIS/alunos.csv', index=False)
df_estado.to_csv('./DADOS_FINAIS/estado.csv', index=False)
df_municipio.to_csv('./DADOS_FINAIS/municipio.csv', index=False)
df_resultados_metas.to_csv('./DADOS_FINAIS/resultados e metas.csv', index=False)